# Generated by Django 3.2 on 2023-10-24 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя использует недопустимый символ', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя (логин)'),
        ),
    ]
