# Generated by Django 3.2 on 2023-10-25 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231024_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя использует недопустимый символ', regex='^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя (логин)'),
            preserve_default=False,
        ),
    ]
