# Generated by Django 3.2 on 2023-10-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_unique_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_fields',
        ),
    ]
