# Generated by Django 3.2 on 2023-11-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231104_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь'), ('superuser', 'Суперпользователь')], default='user', max_length=50, verbose_name='Роль'),
        ),
    ]
