# Generated by Django 3.2.15 on 2023-10-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'verbose_name': 'Произведение-Жанр', 'verbose_name_plural': 'Произведения-Жанры'},
        ),
    ]
