# Generated by Django 3.2 on 2023-10-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='No description provided', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=2023, max_length=256, verbose_name='Название произведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_field', to='reviews.rating'),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Год выхода произведения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_field', to='reviews.title', verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title', 'author')},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
