# Generated by Django 3.2 on 2023-10-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20231029_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug',)},
        ),
    ]
