# Generated by Django 3.2 on 2023-10-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('slug',)},
        ),
    ]
