# Generated by Django 3.2 on 2023-10-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_rating', to='reviews.rating'),
        ),
    ]
