# Generated by Django 3.2 on 2023-10-31 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AddField(
            model_name='rating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_rating', to='reviews.title', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_rating', to='reviews.rating'),
        ),
    ]
