# Generated by Django 3.2 on 2023-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20231031_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_score',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
