# Generated by Django 3.2 on 2023-10-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20231031_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title_rating', to='reviews.rating'),
            preserve_default=False,
        ),
    ]
